spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

fileRepositoryFolder: C:\\Users\\user\\Desktop\\FileRepo